# Generated by Django 2.1.7 on 2019-03-22 05:34

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nested_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_category', to='bulletin_board.Category'),
        ),
    ]
