# Generated by Django 2.1.7 on 2019-03-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_auto_20190322_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.Category'),
        ),
    ]
