# Generated by Django 2.1.7 on 2019-03-24 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0005_auto_20190324_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.Category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='in_favorites',
            field=models.ManyToManyField(blank=True, related_name='in_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
